[package]
name = "mimas-meshgen"
version = "0.4.0"
authors = ["est31 <MTest31@outlook.com>"]

[lib]
name = "mimas_meshgen"
path = "lib.rs"

[dependencies]
nalgebra = "0.21"
glium = "0.27"
mimas-server = { path = "../mimas-server" }
