[package]
name = "mimas-meshgen"
version = "0.5.0-dev"
authors = ["est31 <MTest31@outlook.com>"]

[lib]
name = "mimas_meshgen"
path = "lib.rs"

[dependencies]
nalgebra = "0.22"
glium = "0.28"
mimas-common = { path = "../mimas-common" }
