[package]
name = "mehlon-meshgen"
version = "0.4.0-dev"
authors = ["est31 <MTest31@outlook.com>"]

[lib]
name = "mehlon_meshgen"
path = "lib.rs"

[dependencies]
nalgebra = "0.20"
glium = "0.26"
mehlon-server = { path = "../mehlon-server" }
