override-default = true

[[block]]
name = "default:air"
color = false
pointable = false
solid = false

[[block]]
name = "default:ground"
texture = "assets/textures/default_dirt.png"

[[block]]
name = "default:ground_with_grass"
drops = "default:ground 1"
texture = [
	"assets/textures/default_dirt.png^assets/textures/default_grass_side.png",
	"assets/textures/default_grass.png",
	"assets/textures/default_dirt.png"
]

[[block]]
name = "default:sand"
texture = "assets/textures/default_sand.png"

[[block]]
name = "default:water"
texture = "assets/textures/default_water.png"

[[block]]
name = "default:wood"
texture = "assets/textures/default_wood.png"

[[block]]
name = "default:stone"
drops = "default:cobble 1"
texture = "assets/textures/default_stone.png"

[[block]]
name = "default:cobble"
texture = "assets/textures/default_cobble.png"

[[block]]
name = "default:tree"
texture = [
	"assets/textures/default_tree.png",
	"assets/textures/default_tree_top.png"
]

[[block]]
name = "default:leaves"
texture = "assets/textures/default_leaves.png"

[[block]]
name = "default:cactus"
texture = [
	"assets/textures/default_cactus_side.png",
	"assets/textures/default_cactus_top.png"
]

[[block]]
name = "default:coal"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_coal.png"

[[block]]
name = "default:iron_ore"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_iron.png"

[[block]]
name = "default:copper_ore"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_copper.png"

[[block]]
name = "default:gold_ore"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_gold.png"

[[block]]
name = "default:diamond_ore"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_diamond.png"

[[block]]
name = "default:chest"
texture = [
	"assets/textures/default_chest_side.png",
	"assets/textures/default_chest_top.png"
]
inventory = 40

[[recipe]]
inputs = ["default:tree"]
output = "default:wood 4"

[[recipe]]
inputs = [
	"default:wood", "default:wood", "default:wood",
	"default:wood", "", "default:wood",
	"default:wood", "default:wood", "default:wood",
]
output = "default:chest 1"

[[mapgen.ore]]
name = "default:coal"
noise_seed = "noi-coal"
pcg_seed = "pcg-coal"
freq = 0.083951
pcg_limit = 0.6
limit_a = 0.75
limit_b = 0.5
limit_boundary = -30

[[mapgen.ore]]
name = "default:iron_ore"
noise_seed = "noi-iron"
pcg_seed = "pcg-iron"
freq = 0.063951
pcg_limit = 0.6
limit_a = 0.83
limit_b = 0.7
limit_boundary = -60

[[mapgen.ore]]
name = "default:copper_ore"
noise_seed = "noi-copp"
pcg_seed = "pcg-copp"
freq = 0.083961
pcg_limit = 0.6
limit_a = 2.0
limit_b = 0.8
limit_boundary = -90

[[mapgen.ore]]
name = "default:gold_ore"
noise_seed = "noi-gold"
pcg_seed = "pcg-gold"
freq = 0.083961
pcg_limit = 0.8
limit_a = 2.0
limit_b = 0.86
limit_boundary = -120

[[mapgen.ore]]
name = "default:diamond_ore"
noise_seed = "noi-diam"
pcg_seed = "pcg-diam"
freq =  0.083961
pcg_limit = 0.88
limit_a = 2.0
limit_b = 0.88
limit_boundary = -240

[[block]]
name = "default:grass_1"
drops = "default:grass_3 1"
crossed = true
texture = "assets/textures/default_grass_1.png"

[[block]]
name = "default:grass_2"
drops = "default:grass_3 1"
crossed = true
texture = "assets/textures/default_grass_2.png"

[[block]]
name = "default:grass_3"
drops = "default:grass_3 1"
crossed = true
texture = "assets/textures/default_grass_3.png"

[[block]]
name = "default:grass_4"
drops = "default:grass_3 1"
crossed = true
texture = "assets/textures/default_grass_4.png"

[[block]]
name = "default:grass_5"
drops = "default:grass_3 1"
crossed = true
texture = "assets/textures/default_grass_5.png"

[[mapgen.plant]]
name = "default:grass_1"
pcg_seed = "grass  1"
pcg_limit = 0.996

[[mapgen.plant]]
name = "default:grass_2"
pcg_seed = "grass  2"
pcg_limit = 0.996

[[mapgen.plant]]
name = "default:grass_3"
pcg_seed = "grass  3"
pcg_limit = 0.996

[[mapgen.plant]]
name = "default:grass_4"
pcg_seed = "grass  4"
pcg_limit = 0.996

[[mapgen.plant]]
name = "default:grass_5"
pcg_seed = "grass  5"
pcg_limit = 0.996

## Flowers

[[block]]
name = "flowers:dandelion_white"
crossed = true
texture = "assets/textures/flowers_dandelion_white.png"

[[block]]
name = "flowers:dandelion_yellow"
crossed = true
texture = "assets/textures/flowers_dandelion_yellow.png"

[[block]]
name = "flowers:geranium"
crossed = true
texture = "assets/textures/flowers_geranium.png"

[[block]]
name = "flowers:rose"
crossed = true
texture = "assets/textures/flowers_rose.png"

[[block]]
name = "flowers:tulip_black"
crossed = true
texture = "assets/textures/flowers_tulip_black.png"

[[block]]
name = "flowers:tulip"
crossed = true
texture = "assets/textures/flowers_tulip.png"

[[block]]
name = "flowers:chrysanthemum_green"
crossed = true
texture = "assets/textures/flowers_chrysanthemum_green.png"

[[block]]
name = "flowers:viola"
crossed = true
texture = "assets/textures/flowers_viola.png"

[[mapgen.plant]]
name = "flowers:dandelion_white"
pcg_seed = "dandelio"
pcg_limit = 0.9988

[[mapgen.plant]]
name = "flowers:dandelion_yellow"
pcg_seed = "dandeliy"
pcg_limit = 0.99995

[[mapgen.plant]]
name = "flowers:geranium"
pcg_seed = "geranium"
pcg_limit = 0.99998

[[mapgen.plant]]
name = "flowers:rose"
pcg_seed = "rose    "
pcg_limit = 0.99978

[[mapgen.plant]]
name = "flowers:tulip_black"
pcg_seed = "tulip_bl"
pcg_limit = 0.9999998

[[mapgen.plant]]
name = "flowers:tulip"
pcg_seed = "tulip   "
pcg_limit = 0.99978

[[mapgen.plant]]
name = "flowers:chrysanthemum_green"
pcg_seed = "crysanth"
pcg_limit = 0.9999988

[[mapgen.plant]]
name = "flowers:viola"
pcg_seed = "viola   "
pcg_limit = 0.99962
