override-default = true

[[block]]
name = "default:air"
color = false
pointable = false
solid = false

[[block]]
name = "default:ground"
texture = "assets/textures/default_dirt.png"

[[block]]
name = "default:ground_with_grass"
drops = "default:ground 1"
texture = [
	"assets/textures/default_dirt.png^assets/textures/default_grass_side.png",
	"assets/textures/default_grass.png",
	"assets/textures/default_dirt.png"
]

[[block]]
name = "default:sand"
texture = "assets/textures/default_sand.png"

[[block]]
name = "default:water"
texture = "assets/textures/default_water.png"

[[block]]
name = "default:wood"
texture = "assets/textures/default_wood.png"

[[block]]
name = "default:stone"
dig_group = "default:group_stone 2"
drops = "default:cobble 1"
texture = "assets/textures/default_stone.png"

[[block]]
name = "default:cobble"
dig_group = "default:group_stone 2"
texture = "assets/textures/default_cobble.png"

## Ores

[[block]]
name = "default:coal"
dig_group = "default:group_stone 2"
drops = "default:coal_lump 1"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_coal.png"

[[block]]
name = "default:iron_ore"
dig_group = "default:group_stone 2"
drops = "default:iron_lump 1"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_iron.png"

[[block]]
name = "default:copper_ore"
dig_group = "default:group_stone 3"
drops = "default:copper_lump 1"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_copper.png"

[[block]]
name = "default:tin_ore"
dig_group = "default:group_stone 3"
drops = "default:tin_lump 1"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_tin.png"

[[block]]
name = "default:gold_ore"
dig_group = "default:group_stone 4"
drops = "default:gold_lump 1"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_gold.png"

[[block]]
name = "default:diamond_ore"
dig_group = "default:group_stone 5"
drops = "default:diamond 1"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_diamond.png"

[[block]]
name = "default:coal_lump"
inv_texture = "assets/textures/default_coal_lump.png"
placeable = false

[[block]]
name = "default:iron_lump"
inv_texture = "assets/textures/default_iron_lump.png"
placeable = false

[[block]]
name = "default:copper_lump"
inv_texture = "assets/textures/default_copper_lump.png"
placeable = false

[[block]]
name = "default:tin_lump"
inv_texture = "assets/textures/default_tin_lump.png"
placeable = false

[[block]]
name = "default:gold_lump"
inv_texture = "assets/textures/default_gold_lump.png"
placeable = false

[[block]]
name = "default:diamond"
inv_texture = "assets/textures/default_diamond.png"
placeable = false

[[block]]
name = "default:chest"
texture = [
	"assets/textures/default_chest_side.png",
	"assets/textures/default_chest_top.png"
]
inventory = 40

[[recipe]]
inputs = ["default:tree"]
output = "default:wood 4"

[[recipe]]
inputs = [
	"default:wood", "default:wood", "default:wood",
	"default:wood", "", "default:wood",
	"default:wood", "default:wood", "default:wood",
]
output = "default:chest 1"

[[mapgen.ore]]
name = "default:coal"
noise_seed = "noi-coal"
pcg_seed = "pcg-coal"
freq = 0.083951
pcg_limit = 0.6
limit_a = 0.75
limit_b = 0.5
limit_boundary = -30

[[mapgen.ore]]
name = "default:iron_ore"
noise_seed = "noi-iron"
pcg_seed = "pcg-iron"
freq = 0.063951
pcg_limit = 0.6
limit_a = 0.83
limit_b = 0.7
limit_boundary = -60

[[mapgen.ore]]
name = "default:copper_ore"
noise_seed = "noi-copp"
pcg_seed = "pcg-copp"
freq = 0.083961
pcg_limit = 0.6
limit_a = 2.0
limit_b = 0.8
limit_boundary = -90

[[mapgen.ore]]
name = "default:tin_ore"
noise_seed = "noi--tin"
pcg_seed = "pcg--tin"
freq = 0.083961
pcg_limit = 0.7
limit_a = 2.0
limit_b = 0.8
limit_boundary = -98

[[mapgen.ore]]
name = "default:gold_ore"
noise_seed = "noi-gold"
pcg_seed = "pcg-gold"
freq = 0.083961
pcg_limit = 0.8
limit_a = 2.0
limit_b = 0.86
limit_boundary = -120

[[mapgen.ore]]
name = "default:diamond_ore"
noise_seed = "noi-diam"
pcg_seed = "pcg-diam"
freq =  0.083961
pcg_limit = 0.88
limit_a = 2.0
limit_b = 0.88
limit_boundary = -240

# Ingot Blocks

[[block]]
name = "default:steel_block"
dig_group = "default:group_stone 3"
texture = "assets/textures/default_steel_block.png"

[[block]]
name = "default:copper_block"
dig_group = "default:group_stone 3"
texture = "assets/textures/default_copper_block.png"

[[block]]
name = "default:tin_block"
dig_group = "default:group_stone 3"
texture = "assets/textures/default_tin_block.png"

[[block]]
name = "default:bronze_block"
dig_group = "default:group_stone 3"
texture = "assets/textures/default_bronze_block.png"

[[block]]
name = "default:gold_block"
dig_group = "default:group_stone 3"
texture = "assets/textures/default_gold_block.png"

[[block]]
name = "default:diamond_block"
dig_group = "default:group_stone 4"
texture = "assets/textures/default_diamond_block.png"

[[recipe]]
inputs = [
	"default:steel_ingot", "default:steel_ingot", "default:steel_ingot",
	"default:steel_ingot", "default:steel_ingot", "default:steel_ingot",
	"default:steel_ingot", "default:steel_ingot", "default:steel_ingot",
]
output = "default:steel_block 1"

[[recipe]]
inputs = [
	"default:steel_block",
]
output = "default:steel_ingot 9"

[[recipe]]
inputs = [
	"default:copper_ingot", "default:copper_ingot", "default:copper_ingot",
	"default:copper_ingot", "default:copper_ingot", "default:copper_ingot",
	"default:copper_ingot", "default:copper_ingot", "default:copper_ingot",
]
output = "default:copper_block 1"

[[recipe]]
inputs = [
	"default:copper_block",
]
output = "default:copper_ingot 9"

[[recipe]]
inputs = [
	"default:tin_ingot", "default:tin_ingot", "default:tin_ingot",
	"default:tin_ingot", "default:tin_ingot", "default:tin_ingot",
	"default:tin_ingot", "default:tin_ingot", "default:tin_ingot",
]
output = "default:tin_block 1"

[[recipe]]
inputs = [
	"default:tin_block",
]
output = "default:tin_ingot 9"

[[recipe]]
inputs = [
	"default:bronze_ingot", "default:bronze_ingot", "default:bronze_ingot",
	"default:bronze_ingot", "default:bronze_ingot", "default:bronze_ingot",
	"default:bronze_ingot", "default:bronze_ingot", "default:bronze_ingot",
]
output = "default:bronze_block 1"

[[recipe]]
inputs = [
	"default:bronze_block",
]
output = "default:bronze_ingot 9"

[[recipe]]
inputs = [
	"default:gold_ingot", "default:gold_ingot", "default:gold_ingot",
	"default:gold_ingot", "default:gold_ingot", "default:gold_ingot",
	"default:gold_ingot", "default:gold_ingot", "default:gold_ingot",
]
output = "default:gold_block 1"

[[recipe]]
inputs = [
	"default:gold_block",
]
output = "default:gold_ingot 9"

[[recipe]]
inputs = [
	"default:diamond", "default:diamond", "default:diamond",
	"default:diamond", "default:diamond", "default:diamond",
	"default:diamond", "default:diamond", "default:diamond",
]
output = "default:diamond_block 1"

[[recipe]]
inputs = [
	"default:diamond_block",
]
output = "default:diamond 9"

# Ingots

[[block]]
name = "default:steel_ingot"
inv_texture = "assets/textures/default_steel_ingot.png"
placeable = false

[[block]]
name = "default:copper_ingot"
inv_texture = "assets/textures/default_copper_ingot.png"
placeable = false

[[block]]
name = "default:tin_ingot"
inv_texture = "assets/textures/default_tin_ingot.png"
placeable = false

[[block]]
name = "default:bronze_ingot"
inv_texture = "assets/textures/default_bronze_ingot.png"
placeable = false

[[block]]
name = "default:gold_ingot"
inv_texture = "assets/textures/default_gold_ingot.png"
placeable = false

# Ingot crafts
# TODO once we have furnaces, make furnaces craft them

[[recipe]]
inputs = [
	"default:iron_lump"
]
output = "default:steel_ingot 1"

[[recipe]]
inputs = [
	"default:copper_lump"
]
output = "default:copper_ingot 1"

[[recipe]]
inputs = [
	"default:copper_ingot"
]
output = "default:bronze_ingot 1"

[[recipe]]
inputs = [
	"default:gold_lump"
]
output = "default:gold_ingot 1"

# Items

[[block]]
name = "default:stick"
inv_texture = "assets/textures/default_stick.png"
placeable = false

[[recipe]]
inputs = [
	"default:wood"
]
output = "default:stick 4"

# Tools

[[block]]
name = "default:pick_wood"
inv_texture = "assets/textures/default_tool_woodpick.png"
tool_groups = [{ group = "default:group_stone", speed = 0.5, hardness = 2 }]
placeable = false

[[block]]
name = "default:pick_cobble"
inv_texture = "assets/textures/default_tool_stonepick.png"
tool_groups = [{ group = "default:group_stone", speed = 1.5, hardness = 3 }]
placeable = false

[[block]]
name = "default:pick_iron"
inv_texture = "assets/textures/default_tool_steelpick.png"
tool_groups = [{ group = "default:group_stone", speed = 3.0, hardness = 5 }]
placeable = false

[[block]]
name = "default:pick_bronze"
inv_texture = "assets/textures/default_tool_bronzepick.png"
tool_groups = [{ group = "default:group_stone", speed = 3.0, hardness = 4 }]
placeable = false

[[block]]
name = "default:pick_gold"
inv_texture = "assets/textures/default_tool_mesepick.png"
tool_groups = [{ group = "default:group_stone", speed = 3.0, hardness = 2 }]
placeable = false

[[block]]
name = "default:pick_diamond"
inv_texture = "assets/textures/default_tool_diamondpick.png"
tool_groups = [{ group = "default:group_stone", speed = 5.0, hardness = 6 }]
placeable = false

[[recipe]]
inputs = [
	"default:wood", "default:wood", "default:wood",
	"default:wood", "default:stick", "",
	"default:wood", "", "default:stick",
]
output = "default:pick_wood 1"

[[recipe]]
inputs = [
	"default:cobble", "default:cobble", "default:cobble",
	"default:cobble", "default:stick", "",
	"default:cobble", "", "default:stick",
]
output = "default:pick_cobble 1"

[[recipe]]
inputs = [
	"default:steel_ingot", "default:steel_ingot", "default:steel_ingot",
	"default:steel_ingot", "default:stick", "",
	"default:steel_ingot", "", "default:stick",
]
output = "default:pick_iron 1"

[[recipe]]
inputs = [
	"default:bronze_ingot", "default:bronze_ingot", "default:bronze_ingot",
	"default:bronze_ingot", "default:stick", "",
	"default:bronze_ingot", "", "default:stick",
]
output = "default:pick_bronze 1"

[[recipe]]
inputs = [
	"default:gold_ingot", "default:gold_ingot", "default:gold_ingot",
	"default:gold_ingot", "default:stick", "",
	"default:gold_ingot", "", "default:stick",
]
output = "default:pick_gold 1"

[[recipe]]
inputs = [
	"default:diamond", "default:diamond", "default:diamond",
	"default:diamond", "default:stick", "",
	"default:diamond", "", "default:stick",
]
output = "default:pick_diamond 1"

## Plants

[[block]]
name = "default:tree"
texture = [
	"assets/textures/default_tree.png",
	"assets/textures/default_tree_top.png"
]

[[block]]
name = "default:leaves"
texture = "assets/textures/default_leaves.png"

[[block]]
name = "default:cactus"
texture = [
	"assets/textures/default_cactus_side.png",
	"assets/textures/default_cactus_top.png"
]

[[block]]
name = "default:sapling"
texture = "assets/textures/default_sapling.png"
crossed = true
solid = false

[[recipe]]
inputs = [
	"default:leaves", "default:leaves",
	"default:leaves", "default:leaves",
]
output = "default:sapling 1"

## Grass

[[block]]
name = "default:grass_1"
drops = "default:grass_3 1"
crossed = true
solid = false
texture = "assets/textures/default_grass_1.png"

[[block]]
name = "default:grass_2"
drops = "default:grass_3 1"
crossed = true
solid = false
texture = "assets/textures/default_grass_2.png"

[[block]]
name = "default:grass_3"
drops = "default:grass_3 1"
crossed = true
solid = false
texture = "assets/textures/default_grass_3.png"

[[block]]
name = "default:grass_4"
drops = "default:grass_3 1"
crossed = true
solid = false
texture = "assets/textures/default_grass_4.png"

[[block]]
name = "default:grass_5"
drops = "default:grass_3 1"
crossed = true
solid = false
texture = "assets/textures/default_grass_5.png"

[[mapgen.plant]]
name = "default:grass_1"
pcg_seed = "grass  1"
pcg_limit = 0.996

[[mapgen.plant]]
name = "default:grass_2"
pcg_seed = "grass  2"
pcg_limit = 0.996

[[mapgen.plant]]
name = "default:grass_3"
pcg_seed = "grass  3"
pcg_limit = 0.996

[[mapgen.plant]]
name = "default:grass_4"
pcg_seed = "grass  4"
pcg_limit = 0.996

[[mapgen.plant]]
name = "default:grass_5"
pcg_seed = "grass  5"
pcg_limit = 0.996

## Flowers

[[block]]
name = "flowers:dandelion_white"
crossed = true
solid = false
texture = "assets/textures/flowers_dandelion_white.png"

[[block]]
name = "flowers:dandelion_yellow"
crossed = true
solid = false
texture = "assets/textures/flowers_dandelion_yellow.png"

[[block]]
name = "flowers:geranium"
crossed = true
solid = false
texture = "assets/textures/flowers_geranium.png"

[[block]]
name = "flowers:rose"
crossed = true
solid = false
texture = "assets/textures/flowers_rose.png"

[[block]]
name = "flowers:tulip_black"
crossed = true
solid = false
texture = "assets/textures/flowers_tulip_black.png"

[[block]]
name = "flowers:tulip"
crossed = true
solid = false
texture = "assets/textures/flowers_tulip.png"

[[block]]
name = "flowers:chrysanthemum_green"
crossed = true
solid = false
texture = "assets/textures/flowers_chrysanthemum_green.png"

[[block]]
name = "flowers:viola"
crossed = true
solid = false
texture = "assets/textures/flowers_viola.png"

[[mapgen.plant]]
name = "flowers:dandelion_white"
pcg_seed = "dandelio"
pcg_limit = 0.9988

[[mapgen.plant]]
name = "flowers:dandelion_yellow"
pcg_seed = "dandeliy"
pcg_limit = 0.99995

[[mapgen.plant]]
name = "flowers:geranium"
pcg_seed = "geranium"
pcg_limit = 0.99998

[[mapgen.plant]]
name = "flowers:rose"
pcg_seed = "rose    "
pcg_limit = 0.99978

[[mapgen.plant]]
name = "flowers:tulip_black"
pcg_seed = "tulip_bl"
pcg_limit = 0.9999998

[[mapgen.plant]]
name = "flowers:tulip"
pcg_seed = "tulip   "
pcg_limit = 0.99978

[[mapgen.plant]]
name = "flowers:chrysanthemum_green"
pcg_seed = "crysanth"
pcg_limit = 0.9999988

[[mapgen.plant]]
name = "flowers:viola"
pcg_seed = "viola   "
pcg_limit = 0.99962
