[package]
name = "mehlon-server"
version = "0.2.0-dev"
authors = ["est31 <MTest31@outlook.com>"]

[[bin]]
name = "mehlon-server"
path = "main.rs"

[lib]
name = "mehlon_server"
path = "lib.rs"

[dependencies]
noise = "0.5"
nalgebra = { version = "0.17", features = ["serde-serialize"] }
rand_pcg = "0.1.1"
rand = "0.6.0"
lazy_static = "1.0"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
serde-big-array = "0.1"
structopt = "0.2"
fasthash = "0.3"
toml = "0.4"

# For the networking
webpki = "0.19"
rustls = { version = "0.15", features = ["dangerous_configuration"] }
tokio = "0.1.6"
futures = "0.1.21"
tokio-current-thread = "0.1"
quinn = "0.2"
slog-term = "2"
slog = "2.2"
rcgen = "0.2"

# For map storage
rusqlite = "0.16.0"
libsqlite3-sys = "0.11.0"
byteorder = "1.0"
flate2 = "1.0"
