[package]
name = "mehlon-server"
version = "0.1.0"
authors = ["est31 <MTest31@outlook.com>"]

[lib]
name = "mehlon_server"
path = "lib.rs"

[dependencies]
noise = "0.5"
nalgebra = "0.16"
ncollide3d = "0.17.2"
nphysics3d = "0.9.0"
num-traits = "0.2"
rand_pcg = "0.1.1"
rand = "0.6.0"
lazy_static = "1.0"
