[package]
name = "mehlon-server"
version = "0.1.0"
authors = ["est31 <MTest31@outlook.com>"]

[[bin]]
name = "mehlon-server"
path = "main.rs"

[lib]
name = "mehlon_server"
path = "lib.rs"

[dependencies]
noise = "0.5"
nalgebra = { version = "0.16", features = ["serde-serialize"] }
num-traits = "0.2"
rand_pcg = "0.1.1"
rand = "0.6.0"
lazy_static = "1.0"
serde = "1.0"
serde_derive = "1.0"
bincode = "1.0"
serde-big-array = "0.1"
structopt = "0.2"
fasthash = "0.2"
