[[block]]
name = "Air"
color = false
pointable = false

[[block]]
name = "Ground"
color = [0.0, 1.0, 0.0, 1.0]

[[block]]
name = "Sand"
color = [1.0, 1.0, 0.3, 1.0]

[[block]]
name = "Water"
color = [0.0, 0.0, 1.0, 1.0]

[[block]]
name = "Wood"
color = [0.5, 0.25, 0.0, 1.0]

[[block]]
name = "Stone"
color = [0.5, 0.5, 0.5, 1.0]

[[block]]
name = "Tree"
color = [0.38, 0.25, 0.125, 1.0]

[[block]]
name = "Leaves"
color = [0.0, 0.4, 0.0, 1.0]

[[block]]
name = "Cactus"
color = [0.0, 0.2, 0.0, 1.0]

[[block]]
name = "Coal"
color = [0.05, 0.05, 0.05, 1.0]

[[block]]
name = "IronOre"
color = [0.4, 0.30, 0.0, 1.0]

[[recipe]]
inputs = ["Tree"]
output-itm = "Wood"
output-qty = 4
