override-default = true

[[block]]
name = "default:air"
color = false
pointable = false

[[block]]
name = "default:ground"
texture = [
	"assets/textures/default_dirt.png^assets/textures/default_grass_side.png",
	"assets/textures/default_grass.png",
	"assets/textures/default_dirt.png"
]

[[block]]
name = "default:sand"
texture = "assets/textures/default_sand.png"

[[block]]
name = "default:water"
texture = "assets/textures/default_water.png"

[[block]]
name = "default:wood"
texture = "assets/textures/default_wood.png"

[[block]]
name = "default:stone"
texture = "assets/textures/default_stone.png"

[[block]]
name = "default:tree"
texture = [
	"assets/textures/default_tree.png",
	"assets/textures/default_tree_top.png"
]

[[block]]
name = "default:leaves"
texture = "assets/textures/default_leaves.png"

[[block]]
name = "default:cactus"
texture = [
	"assets/textures/default_cactus_side.png",
	"assets/textures/default_cactus_top.png"
]

[[block]]
name = "default:coal"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_coal.png"

[[block]]
name = "default:iron_ore"
texture = "assets/textures/default_stone.png^assets/textures/default_mineral_iron.png"

[[recipe]]
inputs = ["default:tree"]
output = "default:wood 4"
