[package]
name = "mehlon"
version = "0.1.0"
authors = ["est31 <MTest31@outlook.com>"]

[[bin]]
name = "mehlon"
path = "main.rs"

[dependencies]
noise = "0.5"
nalgebra = "0.16"
ncollide3d = "0.17.2"
nphysics3d = "0.9.0"
num-traits = "0.2"
frustum_query = "0.1"
glium = "0.22"
winit = "0.16"
#glium-glyph = { path = "../glium-glyph" }
#glium-glyph = { git = "https://github.com/est31/glium-glyph" }
glium-glyph = "0.2"
line_drawing = "0.7"
rand_pcg = "0.1.1"
rand = "0.6.0"
mehlon-server = { path = "../mehlon-server" }
