name: mimas

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        toolchain: [stable, beta, 1.51.0]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Install Rust
      if: matrix.os != 'macOS-latest'
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}
        override: true
    - name: Run cargo check
      run: |
        cargo check --verbose --all
    - name: Run release build
      run: |
        cargo build --release
    - name: Run tests
      run: |
        cargo test --all
